### ISSUE TITLE
Create a Page for Internal Judge: Automatic Marking - Question 5

### ISSUE THREAD

**Issue by gdsc-mmcoe** [Google-Developer-Student-Club-CCOEW/Android-2023-GDSC-CUMMINS-X-GDSC-MMCOE#32]
# Create a Page for Internal Judge: Automatic Marking - Question 5

Hello contributors!

### Task
📝 **Task**: Your responsibility is to create a page for the internal judge that will facilitate automatic marking for Question 5. The page should include the following question and radio buttons for judges to select their evaluation.

### You have to contribute to the following files:
- [XML Layout](https://github.com/Google-Developer-Student-Club-CCOEW/Android-2023-GDSC-CUMMINS-X-GDSC-MMCOE/blob/main/SIH%20Evaluation/app/src/main/res/layout/int_auto_que5.xml)
- [Java File](https://github.com/Google-Developer-Student-Club-CCOEW/Android-2023-GDSC-CUMMINS-X-GDSC-MMCOE/blob/main/SIH%20Evaluation/app/src/main/java/com/example/sihevaluation/In_auto_que5.java)

### Question 5: Does the project use cutting-edge technologies or techniques? Rate this on a scale of 1 to 10.
Please implement radio buttons to capture the judge's response to this question. The options are as follows:

- [ ] i) Yes, new technologies are used.
- [ ] ii) Works with current technologies.
- [ ] iii) No advanced or cutting-edge technologies were used.

### Automatic Marking
The radio buttons will allow judges to select their evaluation of whether the project uses cutting-edge technologies or techniques on a scale of 1 to 10.

Please ensure that the user interface is user-friendly and intuitive for judges to use.

Thank you for your contribution! 🚀
